"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useWizard } from "@/lib/store";
import { downloadText } from "@/lib/utils";
import { Download, RotateCcw, Copy, PartyPopper } from "lucide-react";
import { toast } from "sonner";

export function StepExportEnv() {
  const { apiKey, entitySecret, walletSetId, wallet, prev, reset } = useWizard();

  const env = [
    `# Generated by arc-onboard on ${new Date().toISOString()}`,
    `CIRCLE_API_KEY=${apiKey}`,
    `CIRCLE_ENTITY_SECRET=${entitySecret}`,
    `CIRCLE_WALLET_SET_ID=${walletSetId}`,
    `CIRCLE_WALLET_ID=${wallet?.id ?? ""}`,
    `CIRCLE_WALLET_ADDRESS=${wallet?.address ?? ""}`,
    `CIRCLE_WALLET_BLOCKCHAIN=${wallet?.blockchain ?? "ARC-TESTNET"}`,
    "",
  ].join("\n");

  const sample = `import { initiateDeveloperControlledWalletsClient } from "@circle-fin/developer-controlled-wallets";

const client = initiateDeveloperControlledWalletsClient({
  apiKey: process.env.CIRCLE_API_KEY!,
  entitySecret: process.env.CIRCLE_ENTITY_SECRET!,
});

const balance = await client.getWalletTokenBalance({
  id: process.env.CIRCLE_WALLET_ID!,
});
console.log(balance.data?.tokenBalances);
`;

  return (
    <div className="space-y-6">
      <div className="flex items-start gap-3">
        <PartyPopper className="h-7 w-7 text-primary" />
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">
            You're set up
          </h1>
          <p className="text-muted-foreground mt-1">
            Download your <code className="font-mono">.env</code> and start
            building. The credentials below were never persisted — they live
            only in this browser tab.
          </p>
        </div>
      </div>

      <Card>
        <CardContent className="p-5 space-y-3">
          <div className="text-xs font-medium uppercase text-muted-foreground">
            .env
          </div>
          <pre className="bg-muted/40 rounded-md p-3 font-mono text-[11px] leading-snug overflow-x-auto">
            {env
              .replace(apiKey, `${apiKey.slice(0, 12)}…`)
              .replace(
                entitySecret,
                `${entitySecret.slice(0, 8)}…${entitySecret.slice(-4)}`
              )}
          </pre>
          <div className="flex flex-wrap gap-2">
            <Button onClick={() => downloadText(".env", env)}>
              <Download className="h-4 w-4" /> Download .env
            </Button>
            <Button
              variant="secondary"
              onClick={async () => {
                await navigator.clipboard.writeText(env);
                toast.success(".env copied to clipboard");
              }}
            >
              <Copy className="h-4 w-4" /> Copy to clipboard
            </Button>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="p-5 space-y-3">
          <div className="text-xs font-medium uppercase text-muted-foreground">
            Quick test
          </div>
          <pre className="bg-muted/40 rounded-md p-3 font-mono text-[11px] leading-snug overflow-x-auto">
            {sample}
          </pre>
          <Button
            variant="secondary"
            size="sm"
            onClick={async () => {
              await navigator.clipboard.writeText(sample);
              toast.success("Snippet copied");
            }}
          >
            <Copy className="h-3.5 w-3.5" /> Copy snippet
          </Button>
        </CardContent>
      </Card>

      <div className="flex items-center justify-between pt-6 border-t">
        <Button variant="ghost" onClick={prev}>
          Back
        </Button>
        <Button
          variant="outline"
          onClick={() => {
            reset();
            toast.success("Wizard reset");
          }}
        >
          <RotateCcw className="h-4 w-4" /> Start over
        </Button>
      </div>
    </div>
  );
}
